name: flutter_faysal_game
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.33.0
  provider: ^6.1.5+1
  get_it: ^9.0.5
  injectable: ^2.6.0
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  flutter_screenutil: ^5.9.3
  logger: ^2.6.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  google_fonts: ^6.3.2
  country_picker: ^2.0.27
  firebase_storage: ^13.0.4
  uuid: ^4.5.2
  file_picker: ^10.3.6
  cloudinary_public: ^0.23.1
  shared_preferences: ^2.5.3
  carousel_slider: ^5.0.0
  percent_indicator: ^4.2.3
  cached_network_image: ^3.4.1
  url_launcher: ^6.2.0
  share_plus: ^12.0.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.9.1
  build_runner: ^2.10.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # Uncomment and add fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
